// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortenr.Data;

namespace UrlShortenr.Migrations
{
    [DbContext(typeof(UrlContext))]
    partial class UrlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("UrlShortenr.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ClickDate");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int?>("UrlId");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("UrlShortenr.Models.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<int>("ClicksCount");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("UrlShortenr.Models.Statistic", b =>
                {
                    b.HasOne("UrlShortenr.Models.Url", "Url")
                        .WithMany("Statistics")
                        .HasForeignKey("UrlId");
                });
#pragma warning restore 612, 618
        }
    }
}
